/**
 * @file    rs485.c
 * @brief   RS485 multi-port driver with ring buffers
 */

#include "rs485.h"
#include "config.h"
#include "stm32f1xx_hal.h"
#include <string.h>

/* External UART handles (generated by CubeMX) */
extern UART_HandleTypeDef huart1;
extern UART_HandleTypeDef huart2;
extern UART_HandleTypeDef huart3;
extern UART_HandleTypeDef huart4;
extern UART_HandleTypeDef huart5;

/* Ring buffer structure */
typedef struct {
    uint8_t  buf[RS485_RING_BUF_SIZE];
    volatile uint16_t head;
    volatile uint16_t tail;
} RingBuf_t;

/* Per-port context */
typedef struct {
    UART_HandleTypeDef *huart;
    GPIO_TypeDef *de_port;
    uint16_t      de_pin;
    RingBuf_t     rx_ring;
    uint8_t       rx_byte;       /* Single-byte RX buffer for IT mode */
    uint8_t       has_de;        /* 1 if DE pin exists */
} Rs485_Port_t;

static Rs485_Port_t s_ports[UART_IDX_COUNT];

/* ---- Ring buffer helpers ---- */

static void ring_init(RingBuf_t *r)
{
    r->head = 0;
    r->tail = 0;
}

static uint16_t ring_count(const RingBuf_t *r)
{
    return (r->head - r->tail) & (RS485_RING_BUF_SIZE - 1);
}

static void ring_put(RingBuf_t *r, uint8_t byte)
{
    uint16_t next = (r->head + 1) & (RS485_RING_BUF_SIZE - 1);
    if (next != r->tail) {   /* Not full */
        r->buf[r->head] = byte;
        r->head = next;
    }
}

static uint8_t ring_get(RingBuf_t *r, uint8_t *byte)
{
    if (r->head == r->tail) return 0;   /* Empty */
    *byte = r->buf[r->tail];
    r->tail = (r->tail + 1) & (RS485_RING_BUF_SIZE - 1);
    return 1;
}

/* ---- Init ---- */

void Rs485_Init(void)
{
    /* USART1: PA9/PA10, DE=PA8 */
    s_ports[UART_IDX_1].huart  = &huart1;
    s_ports[UART_IDX_1].de_port = GPIOA;
    s_ports[UART_IDX_1].de_pin  = GPIO_PIN_8;
    s_ports[UART_IDX_1].has_de  = 1;

    /* USART2: PA2/PA3, DE=PC9 */
    s_ports[UART_IDX_2].huart  = &huart2;
    s_ports[UART_IDX_2].de_port = GPIOC;
    s_ports[UART_IDX_2].de_pin  = GPIO_PIN_9;
    s_ports[UART_IDX_2].has_de  = 1;

    /* USART3: PB10/PB11 (CH395, no DE) */
    s_ports[UART_IDX_3].huart  = &huart3;
    s_ports[UART_IDX_3].de_port = NULL;
    s_ports[UART_IDX_3].de_pin  = 0;
    s_ports[UART_IDX_3].has_de  = 0;

    /* USART4(UART4): PC10/PC11, DE=PA15 */
    s_ports[UART_IDX_4].huart  = &huart4;
    s_ports[UART_IDX_4].de_port = GPIOA;
    s_ports[UART_IDX_4].de_pin  = GPIO_PIN_15;
    s_ports[UART_IDX_4].has_de  = 1;

    /* USART5(UART5): PC12/PD2, DE=PB3 */
    s_ports[UART_IDX_5].huart  = &huart5;
    s_ports[UART_IDX_5].de_port = GPIOB;
    s_ports[UART_IDX_5].de_pin  = GPIO_PIN_3;
    s_ports[UART_IDX_5].has_de  = 1;

    /* Initialize ring buffers and start RX IT on all ports */
    for (int i = 0; i < UART_IDX_COUNT; i++) {
        ring_init(&s_ports[i].rx_ring);
        Rs485_SetDir(i, 0);   /* RX mode */
        HAL_UART_Receive_IT(s_ports[i].huart, &s_ports[i].rx_byte, 1);
    }
}

/* ---- Direction control ---- */

void Rs485_SetDir(uint8_t uart_idx, uint8_t tx_en)
{
    if (uart_idx >= UART_IDX_COUNT) return;
    Rs485_Port_t *p = &s_ports[uart_idx];
    if (!p->has_de) return;

    if (tx_en) {
        HAL_GPIO_WritePin(p->de_port, p->de_pin, GPIO_PIN_SET);
    } else {
        HAL_GPIO_WritePin(p->de_port, p->de_pin, GPIO_PIN_RESET);
    }
}

/* ---- Send ---- */

void Rs485_SendData(uint8_t uart_idx, uint8_t *data, uint16_t len)
{
    if (uart_idx >= UART_IDX_COUNT) return;
    Rs485_Port_t *p = &s_ports[uart_idx];

    /* Enable TX */
    Rs485_SetDir(uart_idx, 1);

    /* Small delay for DE to settle */
    volatile uint32_t dly = 100;
    while (dly--) { __NOP(); }

    HAL_UART_Transmit(p->huart, data, len, 1000);

    /* Wait for TX complete */
    while (__HAL_UART_GET_FLAG(p->huart, UART_FLAG_TC) == RESET) {}

    /* Switch back to RX */
    Rs485_SetDir(uart_idx, 0);
}

/* ---- Receive ---- */

void Rs485_ReadData(uint8_t uart_idx, uint8_t *buf, uint16_t max_len, uint16_t *actual_len)
{
    *actual_len = 0;
    if (uart_idx >= UART_IDX_COUNT) return;
    RingBuf_t *r = &s_ports[uart_idx].rx_ring;

    while (*actual_len < max_len) {
        if (!ring_get(r, &buf[*actual_len])) break;
        (*actual_len)++;
    }
}

void Rs485_FlushRx(uint8_t uart_idx)
{
    if (uart_idx >= UART_IDX_COUNT) return;
    ring_init(&s_ports[uart_idx].rx_ring);
}

/* ---- UART RX Complete Callback ---- */

void Rs485_UartRxCpltCallback(void *huart)
{
    for (int i = 0; i < UART_IDX_COUNT; i++) {
        if (s_ports[i].huart == (UART_HandleTypeDef *)huart) {
            ring_put(&s_ports[i].rx_ring, s_ports[i].rx_byte);
            /* Re-arm RX IT */
            HAL_UART_Receive_IT(s_ports[i].huart, &s_ports[i].rx_byte, 1);
            break;
        }
    }
}
