/**
 * @file    web_resources.c
 * @brief   Embedded web page as C string (auto-generated from index.html)
 */

#include "web_resources.h"

const char web_index_html[] =
    "<!DOCTYPE html>\n<html lang=\"zh-CN\">\n<head>\n<meta charset=\"UTF-8\">\n<meta name=\"viewport\" co"
    "ntent=\"width=device-width, initial-scale=1.0\">\n<title>Modbus Gateway</title>\n<style>\n*{box-sizi"
    "ng:border-box;margin:0;padding:0}\nbody{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Robo"
    "to,sans-serif;background:#f0f2f5;color:#333;padding:20px}\nh1{text-align:center;color:#1890ff;margin"
    "-bottom:20px;font-size:24px}\n.container{max-width:900px;margin:0 auto}\n.card{background:#fff;borde"
    "r-radius:8px;box-shadow:0 2px 8px rgba(0,0,0,0.1);padding:20px;margin-bottom:16px}\n.card h2{font-si"
    "ze:16px;color:#333;margin-bottom:12px;border-bottom:1px solid #eee;padding-bottom:8px}\nlabel{displa"
    "y:block;font-size:13px;color:#666;margin-bottom:4px}\ninput,select{width:100%;padding:6px 10px;borde"
    "r:1px solid #d9d9d9;border-radius:4px;margin-bottom:10px;font-size:14px}\ninput:focus,select:focus{o"
    "utline:none;border-color:#1890ff}\n.row{display:flex;gap:12px}\n.row>*{flex:1}\n.btn{display:inline-"
    "block;padding:8px 24px;background:#1890ff;color:#fff;border:none;border-radius:4px;cursor:pointer;fo"
    "nt-size:14px}\n.btn:hover{background:#40a9ff}\n.btn-danger{background:#ff4d4f}\n.btn-danger:hover{ba"
    "ckground:#ff7875}\ntable{width:100%;border-collapse:collapse;font-size:13px}\nth,td{padding:8px 10px"
    ";border:1px solid #eee;text-align:left}\nth{background:#fafafa;font-weight:600}\n.status-ok{color:#5"
    "2c41a}\n.status-err{color:#ff4d4f}\n</style>\n</head>\n<body>\n<div class=\"container\">\n<h1>Modbus"
    " Gateway Configuration</h1>\n\n<div class=\"card\">\n<h2>System Status</h2>\n<div id=\"status-area\""
    ">Loading...</div>\n<button class=\"btn\" onclick=\"refreshStatus()\">Refresh</button>\n</div>\n\n<di"
    "v class=\"card\">\n<h2>System Parameters</h2>\n<div class=\"row\">\n<div>\n<label>Slave Address</lab"
    "el>\n<input type=\"number\" id=\"slaveAddr\" min=\"1\" max=\"247\" value=\"1\">\n</div>\n<div>\n<lab"
    "el>Poll Interval (ms)</label>\n<input type=\"number\" id=\"pollInterval\" min=\"100\" max=\"60000\" "
    "value=\"4000\">\n</div>\n</div>\n<div class=\"row\">\n<div>\n<label>Collect Baud</label>\n<select id"
    "=\"collectBaud\">\n<option value=\"9600\">9600</option>\n<option value=\"19200\">19200</option>\n<op"
    "tion value=\"38400\">38400</option>\n<option value=\"57600\">57600</option>\n<option value=\"115200\"
    "" selected>115200</option>\n</select>\n</div>\n<div>\n<label>Forward Baud</label>\n<select id=\"forw"
    "ardBaud\">\n<option value=\"9600\">9600</option>\n<option value=\"19200\">19200</option>\n<option va"
    "lue=\"38400\">38400</option>\n<option value=\"57600\">57600</option>\n<option value=\"115200\" selec"
    "ted>115200</option>\n</select>\n</div>\n</div>\n</div>\n\n<div class=\"card\">\n<h2>Sensor Configura"
    "tion</h2>\n<div class=\"row\">\n<div>\n<label>Sensor Count</label>\n<input type=\"number\" id=\"sens"
    "orCount\" min=\"0\" max=\"4\" value=\"4\">\n</div>\n</div>\n<div id=\"sensor-config\"></div>\n</div>"
    "\n\n<div class=\"card\">\n<h2>Camera Configuration</h2>\n<div id=\"camera-config\"></div>\n</div>\n\"
    "n<div style=\"text-align:center;margin-top:16px\">\n<button class=\"btn\" onclick=\"saveConfig()\">S"
    "ave Configuration</button>\n<button class=\"btn\" onclick=\"loadConfig()\" style=\"margin-left:8px;b"
    "ackground:#52c41a\">Load</button>\n</div>\n</div>\n\n<script>\nvar config = null;\n\nfunction refres"
    "hStatus() {\n    fetch('/api/status').then(r=>r.json()).then(d=>{\n        var h = '<table><tr><th>S"
    "ensor</th><th>Slave Addr</th>';\n        if(d.sensors&&d.sensors.length>0){\n            var keys = "
    "Object.keys(d.sensors[0].data||{});\n            keys.forEach(k=>{h+='<th>'+k+'</th>'});\n        }\"
    "n        h+='</tr>';\n        (d.sensors||[]).forEach((s,i)=>{\n            h+='<tr><td>Sensor '+i+'"
    "</td><td>'+s.addr+'</td>';\n            keys.forEach(k=>{h+='<td>'+(s.data[k]||0)+'</td>'});\n      "
    "      h+='</tr>';\n        });\n        h+='</table>';\n        h+='<p style=\"margin-top:8px;font-s"
    "ize:13px;color:#666\">Total Registers: '+(d.totalRegs||0)+'</p>';\n        document.getElementById('"
    "status-area').innerHTML=h;\n    }).catch(e=>{\n        document.getElementById('status-area').innerH"
    "TML='<span class=\"status-err\">Failed to load</span>';\n    });\n}\n\nfunction renderSensors(n) {\n"
    "    var h='';\n    for(var i=0;i<n;i++){\n        h+='<div style=\"border:1px solid #eee;border-radi"
    "us:4px;padding:12px;margin-bottom:8px\">';\n        h+='<h3 style=\"font-size:14px;margin-bottom:8px"
    "\">Sensor '+i+'</h3>';\n        h+='<div class=\"row\"><div><label>Slave Address</label>';\n        "
    "h+='<input type=\"number\" id=\"s'+i+'addr\" min=\"1\" max=\"247\" value=\"'+(config&&config.sensors"
    "[i]?config.sensors[i].addr:(3+i))+'\">';\n        h+='</div><div><label>Data Points</label>';\n     "
    "   h+='<input type=\"number\" id=\"s'+i+'dp\" min=\"1\" max=\"8\" value=\"'+(config&&config.sensors["
    "i]?config.sensors[i].dpCount:4)+'\">';\n        h+='</div></div></div>';\n    }\n    document.getEle"
    "mentById('sensor-config').innerHTML=h;\n}\n\nfunction renderCameras(n) {\n    var h='';\n    for(var"
    " i=0;i<n;i++){\n        h+='<div style=\"border:1px solid #eee;border-radius:4px;padding:12px;margin"
    "-bottom:8px\">';\n        h+='<h3 style=\"font-size:14px;margin-bottom:8px\">Camera '+i+'</h3>';\n  "
    "      h+='<div class=\"row\"><div><label>IP Address</label>';\n        h+='<input type=\"text\" id=\"
    ""c'+i+'ip\" value=\"'+(config&&config.cameras[i]?config.cameras[i].ip:'192.168.1.64')+'\">';\n      "
    "  h+='</div><div><label>Channel</label>';\n        h+='<input type=\"number\" id=\"c'+i+'ch\" min=\""
    "1\" max=\"16\" value=\"'+(config&&config.cameras[i]?config.cameras[i].channel:1)+'\">';\n        h+="
    "'</div></div></div>';\n    }\n    document.getElementById('camera-config').innerHTML=h;\n}\n\nfuncti"
    "on loadConfig() {\n    fetch('/api/config').then(r=>r.json()).then(d=>{\n        config=d;\n        "
    "document.getElementById('slaveAddr').value=d.slaveAddr||1;\n        document.getElementById('pollInt"
    "erval').value=d.pollInterval||4000;\n        document.getElementById('sensorCount').value=d.sensorCo"
    "unt||4;\n        renderSensors(d.sensorCount||4);\n        renderCameras(d.sensorCount||4);\n    })."
    "catch(e=>{alert('Load failed')});\n}\n\nfunction saveConfig() {\n    var n=parseInt(document.getElem"
    "entById('sensorCount').value)||4;\n    var cfg={\n        sensorCount:n,\n        slaveAddr:parseInt"
    "(document.getElementById('slaveAddr').value)||1,\n        pollInterval:parseInt(document.getElementB"
    "yId('pollInterval').value)||4000,\n        sensors:[],\n        cameras:[]\n    };\n    for(var i=0;"
    "i<n;i++){\n        cfg.sensors.push({\n            addr:parseInt(document.getElementById('s'+i+'addr"
    "').value)||(3+i),\n            dpCount:parseInt(document.getElementById('s'+i+'dp').value)||4\n     "
    "   });\n        cfg.cameras.push({\n            ip:document.getElementById('c'+i+'ip').value||'192.1"
    "68.1.64',\n            channel:parseInt(document.getElementById('c'+i+'ch').value)||1\n        });\n"
    "    }\n    fetch('/api/config',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON."
    "stringify(cfg)})\n    .then(r=>r.json()).then(d=>{\n        if(d.result==='ok'){alert('Saved!')}\n  "
    "      else{alert('Save error')}\n    }).catch(e=>{alert('Save failed')});\n}\n\nwindow.onload=functi"
    "on(){loadConfig();refreshStatus();setInterval(refreshStatus,5000)};\n</script>\n</body>\n</html>\n";

const uint32_t web_index_html_len = sizeof(web_index_html) - 1;
